{
 "title": "Test",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Single Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(metric_name[$__interval_rv])"
    }
   ]
  },
  {
   "title": "Plugin Single Panel",
   "type": "unknown_plugin",
   "targets": [
    {
     "expr": "rate(metric_name[$__interval_rv])"
    }
   ]
  },
  { "title": "Row With Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Panel Inside Row",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(metric_name[$__interval_sx3])"
    }
   ]
  },
  {
   "title": "Plugin Panel Inside Row",
   "type": "unknown_plugin",
   "targets": [
    {
     "expr": "rate(metric_name[$__interval_sx4])"
    }
   ]
  }
 ]
}