---
apiVersion: v1
kind: Service
metadata:
  {{- include "name.namespace" (list $ "webhook") | nindent 2 }}
  {{- include "webhook.labels" . | nindent 2 }}
spec:
  ports:
  - name: https-webhook
    port: 443
    protocol: TCP
    targetPort: 15017
  selector:
    {{- include "webhook.labels" . | nindent 4 }}
  type: ClusterIP