---
apiVersion: v1
kind: Secret
metadata:
  {{- include "name.namespace" (list $ "webhook") | nindent 2 }}
  {{- include "webhook.labels" . | nindent 2 }}
type: kubernetes.io/tls
data:
{{- with .Values.multitenancyManager.internal.webhookCertificate }}
  ca.crt: {{  .ca  | b64enc }}
  tls.crt: {{ .crt | b64enc }}
  tls.key: {{ .key | b64enc }}
{{- end }}
