---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  {{- include "name" (list $ "webhook") | nindent 2 }}
  {{- include "webhook.labels" . | nindent 2 }}
webhooks:
  - name: validate.{{ .Chart.Name }}.projecttypes.deckhouse.io
    rules:
      - apiGroups:
          - "deckhouse.io"
        apiVersions:
          - "v1alpha1"
        resources:
          - "projecttypes"
        operations:
          - CREATE
          - UPDATE
    admissionReviewVersions:
    - v1
    matchPolicy: Equivalent
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      caBundle: {{ .Values.multitenancyManager.internal.webhookCertificate.ca | b64enc }}
      service:
        {{- include "name.namespace" (list $ "webhook") | nindent 8 }}
        path: /validate
