---
apiVersion: v1
kind: Secret
metadata:
  name: deckhouse-registry
  {{- include "namespace" . | nindent 2 }}
  {{- include "labels" (list .) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.modulesImages.registry.dockercfg }}
