# Copyright 2025 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bashible validation

on:
  pull_request:
    paths:
      - "candi/bashible/**/*.tpl"
      - "candi/cloud-providers/**/*.tpl"
  workflow_dispatch:

jobs:
  bashible_validation:
    name: bashible validation
    runs-on: [self-hosted, regular]
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        provider: ["Yandex", "Azure", "AWS", "GCP"]
    steps:
      # <template: import_secrets>
{!{- $secrets := slice -}!}
{!{- $secrets = append ( slice "projects/data/6db2f1ee-9b6f-4f4f-8381-2fb43060478a/github/registry_host" "DECKHOUSE_REGISTRY_READ_HOST" "DECKHOUSE_REGISTRY_READ_HOST" ) $secrets -}!}
{!{- $secrets = append ( slice "projects/data/6db2f1ee-9b6f-4f4f-8381-2fb43060478a/github/registry_read_token" "login" "DECKHOUSE_REGISTRY_READ_USER" ) $secrets -}!}
{!{- $secrets = append ( slice "projects/data/6db2f1ee-9b6f-4f4f-8381-2fb43060478a/github/registry_read_token" "password" "DECKHOUSE_REGISTRY_READ_PASSWORD" ) $secrets -}!}
{!{ tmpl.Exec "import_secrets" $secrets | strings.Indent 6 }!}
  {!{ tmpl.Exec "checkout_step"                . | strings.Indent 6 }!}
  {!{ tmpl.Exec "login_readonly_registry_step" . | strings.Indent 6 }!}
      - name: Bashible validation on ${{ matrix.provider }} provider
        env:
          PROVIDER: ${{ matrix.provider }}
          REGISTRY: ${{steps.secrets.outputs.DECKHOUSE_REGISTRY_READ_HOST}}
        run: |
          ./.github/scripts/validation_bashible.sh
