positive:
  configValues:
    - {}
    # only node selector
    - nodeSelector: { "disk-type": "ssd" }

    # only tolerations
    - tolerations:
        - {
            "key": "dedicated.deckhouse.io",
            "operator": "Equal",
            "value": "cert-manager",
          }
        - {
            "key": "dedicated.deckhouse.io",
            "operator": "Equal",
            "value": "system",
          }

    # node selector with tolerations
    - nodeSelector: { "disk-type": "ssd" }
      tolerations:
        - {
            "key": "dedicated.deckhouse.io",
            "operator": "Equal",
            "value": "cert-manager",
          }
        - {
            "key": "dedicated.deckhouse.io",
            "operator": "Equal",
            "value": "system",
          }
    - locations:
        - location: /
          users:
            admin: secret
  values:
    - {}
negative:
  configValues:
    - { somethingInConfig: yes }
  values:
    - { somethingInConfig: yes }
