"actions/cache": "actions/cache@v2.1.7"
"actions/checkout": "actions/checkout@v2.4.0"
"actions/github-script": "actions/github-script@v5.2.0"
"actions/download-artifact": "actions/download-artifact@v2"
"actions/upload-artifact": "actions/upload-artifact@v2"
"docker/login-action": "docker/login-action@v1.10.0"
"werf/actions/install": "werf/actions/install@v1.2"
"werf/actions/run": "werf/actions/run@v1.2"
"werf/actions/build": "werf/actions/build@v1.2"
"werf/actions/converge": "werf/actions/converge@v1.2"
"dorny/paths-filter": "dorny/paths-filter@v2"
