---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: kube-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" .Chart.Name)) | nindent 2 }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
